[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
test = 'test/foundry/integration/e2e'
solc = '0.8.23'
fs_permissions = [{ access = 'read-write', path = './deploy-out' }, { access = 'read', path = './out' }]
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
# Comment out for local development (testing requires 0xSplit forks — will add Mock soon)
# pin fork by using --fork-block-number 19042069 to reduce wait time
mainnet = "https://rpc.ankr.com/eth"
sepolia = "${SEPOLIA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config